- id: tach
  name: tach
  description: Validate package dependencies
  entry: tach check
  language: python
  pass_filenames: false
- id: tach-external
  name: tach-external
  description: Validate external package dependencies
  entry: tach check-external
  language: python
  pass_filenames: false
